exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # whitespace
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=lf']
    exclude: '.*\.(svg)$'
  - id: check-byte-order-marker
  # file format and permissions
  - id: check-ast
  - id: check-json
  - id: check-xml
  - id: check-yaml
    files: .*\.(yaml|yml)$
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  # git
  - id: check-shebang-scripts-are-executable
  - id: check-added-large-files
  - id: check-case-conflict
  - id: detect-private-key
  # python
  - id: debug-statements
  - id: check-docstring-first
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: fix-encoding-pragma


- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: remove-tabs
      exclude: '.*\.(svg)$'

- repo: https://github.com/PyCQA/bandit
  rev: 1.8.3
  hooks:
    - id: bandit

- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: 1.5.0
  hooks:
    - id: tox-ini-fmt

- repo: https://opendev.org/openstack/bashate
  rev: 2.1.1
  hooks:
    - id: bashate
      args: ["--max-line-length", "150"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
